### PR TITLE
auto set remote origin to git repo

### PR DESCRIPTION
**Pull request by robatipoor**

### CODE REVIEW

**Comment by loganintech** [comment]
Cool idea. However, I don't think it addresses the use-case of users (like me) who use ssh for their remotes. This is particularly important for work scenarios when git uses public key auth by default. I'd be happy to implement this as an additional global flag but I before that happens I have to convert the structopt CLI setup to a fully-loaded Clap app. This will let me add universal commands more easily.

**Comment by loganintech** [comment]
Ok, I modified the way the CLI works so that we can add global params. I'll integrate this idea with one of those.

**Comment by robatipoor** [comment]
Ok thank you i resolve merge conflict

**Comment by loganintech** [comment]
Hey, I went ahead and added an implementation of this in [feature/6](https://github.com/loganintech/gitpub/tree/feature/6). It adds this work behind a CLI param that enables this optionally. Check it out. [This is the commit I added it in specifically.](https://github.com/loganintech/gitpub/commit/c2a6464328a4aa5a75dea8188865fba95d305f2b)

**Comment by loganintech** [comment]
I'm closing this as it's now implemented in master via #7

**Pull request closed without merging**
